DROP TABLE IF EXISTS time_data;

CREATE TABLE time_data(
    date DATE NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    price REAL NOT NULL,
    market_cap REAL NOT NULL,
    fcf_ttm REAL,
    fcf_lq REAL,
    net_income_ttm REAL,
    net_income_lq REAL,
    operating_cash_flow_ttm REAL,
    total_assets REAL,
    beta_5y_mo_end REAL,
    roa_ttm REAL,
    net_income_ly REAL,
    total_assets_ly REAL,
    long_term_debt REAL,
    long_term_debt_ly REAL,
    current_ratio REAL,
    current_assets REAL,
    current_liabilities REAL,
    current_assets_ly REAL,
    current_liabilities_ly REAL,
    current_ratio_ly REAL,
    shares_outstanding REAL,
    shares_outstanding_ly REAL,
    gross_margin_percent_ttm REAL,
    gross_margin_percent_lq REAL,
    gross_margin_percent_ly REAL,
    asset_turnover_ratio REAL,
    asset_turnover_ratio_ly REAL,
    total_debt_to_total_equity_lq REAL,
    total_assets_lq REAL,
    total_revenue_lq REAL,
    roic_percent_ttm REAL,
    ebit_ttm REAL,
    ev REAL,
    p_to_b_daily REAL,
    p_to_e_daily REAL,
    ebita_ttm REAL,
    revenue_ttm REAL,
    operating_expenses_ttm REAL,
    gross_profit_ttm REAL,
    roa_percent_ly REAL,
    total_equity_lq REAL
);

-- \copy test_data FROM 'C:\Users\tss16\OneDrive\Documents\Summer2022\SEED\VTSEED_Quantitative_Strategy\backtesting_strategy_2.0\persistence\data\SP500_Test_Small_Time_1.0.csv' DELIMITER ',' CSV